# Generated by Django 5.1.7 on 2025-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
