# Generated by Django 5.1.4 on 2025-03-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_order_product_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='renter',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_provider',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_renter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
