# Generated by Django 5.1.4 on 2025-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rename_user_order_renter_order_phone_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_provider',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_renter',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
