# Generated by Django 5.1.4 on 2025-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_order_phone_provider_alter_order_phone_renter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_renter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
