# Generated by Django 5.1.4 on 2025-03-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_category_shop_address_shop_contact_shop_postal_code_and_more'),
        ('shops', '0004_shop_address_shop_contact_shop_postal_code'),
    ]

    operations = [
    ]
