# Generated by Django 5.1.4 on 2025-03-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_merge_20250101_0853'),
        ('shops', '0005_merge_20250313_0828'),
    ]

    operations = [
    ]
